/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2018-02-18 19:10:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.include;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class stu_005fsidebar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" <section>\r\n");
      out.write("        <!-- Left Sidebar -->\r\n");
      out.write("        <aside id=\"leftsidebar\" class=\"sidebar\">\r\n");
      out.write("            <!-- User Info -->\r\n");
      out.write("            <div class=\"user-info\">\r\n");
      out.write("                <div class=\"image\">\r\n");
      out.write("                    <img src=\"images/user.png\" width=\"48\" height=\"48\" alt=\"User\" />\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"info-container\">\r\n");
      out.write("                    <div class=\"name\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">John Doe</div>\r\n");
      out.write("                    ");
if(session.getAttribute("email")!=null){
      out.write("\r\n");
      out.write("                    <div class=\"email\">");
      out.print(session.getAttribute("email"));
      out.write("</div>\r\n");
      out.write("                    ");
} 
      out.write("\r\n");
      out.write("                    <div class=\"btn-group user-helper-dropdown\">\r\n");
      out.write("                        <i class=\"material-icons\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"true\">keyboard_arrow_down</i>\r\n");
      out.write("                        <ul class=\"dropdown-menu pull-right\">\r\n");
      out.write("                            <li><a href=\"javascript:void(0);\"><i class=\"material-icons\">person</i>Profile</a></li>\r\n");
      out.write("                            <li role=\"seperator\" class=\"divider\"></li>\r\n");
      out.write("                            <li><a href=\"javascript:void(0);\"><i class=\"material-icons\">group</i>Followers</a></li>\r\n");
      out.write("                            <li><a href=\"javascript:void(0);\"><i class=\"material-icons\">shopping_cart</i>Sales</a></li>\r\n");
      out.write("                            <li><a href=\"javascript:void(0);\"><i class=\"material-icons\">favorite</i>Likes</a></li>\r\n");
      out.write("                            <li role=\"seperator\" class=\"divider\"></li>\r\n");
      out.write("                            <li><a href=\"javascript:void(0);\"><i class=\"material-icons\">input</i>Sign Out</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- #User Info -->\r\n");
      out.write("            <!-- Menu -->\r\n");
      out.write("            <div class=\"menu\">\r\n");
      out.write("                <ul class=\"list\">\r\n");
      out.write("                    <li class=\"header\">MAIN NAVIGATION</li>\r\n");
      out.write("                    <li class=\"active\">\r\n");
      out.write("                        <a href=\"dashboard.jsp\">\r\n");
      out.write("                            <i class=\"material-icons\">home</i>\r\n");
      out.write("                            <span>Dashboard</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    <li >\r\n");
      out.write("                        <a href=\"post_grievance.jsp\">\r\n");
      out.write("                            <i class=\"material-icons\">publish</i>\r\n");
      out.write("                            <span>Post Grievance</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li >\r\n");
      out.write("                        <a href=\"view_grievance.jsp\">\r\n");
      out.write("                            <i class=\"material-icons\">chat</i>\r\n");
      out.write("                            <span>View Grievance</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("                     <li >\r\n");
      out.write("                        <a href=\"VerifyStudentServlet\">\r\n");
      out.write("                            <i class=\"material-icons\">layers</i>\r\n");
      out.write("                            <span>New Student Request</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <!-- <li>\r\n");
      out.write("                        <a href=\"pages/typography.html\">\r\n");
      out.write("                            <i class=\"material-icons\">text_fields</i>\r\n");
      out.write("                            <span>Typography</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"pages/helper-classes.html\">\r\n");
      out.write("                            <i class=\"material-icons\">layers</i>\r\n");
      out.write("                            <span>Helper Classes</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"javascript:void(0);\" class=\"menu-toggle\">\r\n");
      out.write("                            <i class=\"material-icons\">widgets</i>\r\n");
      out.write("                            <span>Widgets</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul class=\"ml-menu\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"javascript:void(0);\" class=\"menu-toggle\">\r\n");
      out.write("                                    <span>Cards</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <ul class=\"ml-menu\">\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <a href=\"pages/widgets/cards/basic.html\">Basic</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <a href=\"pages/widgets/cards/colored.html\">Colored</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <a href=\"pages/widgets/cards/no-header.html\">No Header</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"javascript:void(0);\" class=\"menu-toggle\">\r\n");
      out.write("                                    <span>Infobox</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <ul class=\"ml-menu\">\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <a href=\"pages/widgets/infobox/infobox-1.html\">Infobox-1</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <a href=\"pages/widgets/infobox/infobox-2.html\">Infobox-2</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <a href=\"pages/widgets/infobox/infobox-3.html\">Infobox-3</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <a href=\"pages/widgets/infobox/infobox-4.html\">Infobox-4</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <a href=\"pages/widgets/infobox/infobox-5.html\">Infobox-5</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"javascript:void(0);\" class=\"menu-toggle\">\r\n");
      out.write("                            <i class=\"material-icons\">swap_calls</i>\r\n");
      out.write("                            <span>User Interface (UI)</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul class=\"ml-menu\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"pages/ui/alerts.html\">Alerts</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"pages/ui/animations.html\">Animations</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"pages/ui/badges.html\">Badges</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"pages/ui/breadcrumbs.html\">Breadcrumbs</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"pages/ui/buttons.html\">Buttons</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"pages/ui/collapse.html\">Collapse</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"pages/ui/colors.html\">Colors</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"pages/ui/dialogs.html\">Dialogs</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"pages/ui/icons.html\">Icons</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"pages/ui/labels.html\">Labels</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"pages/ui/list-group.html\">List Group</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"pages/ui/media-object.html\">Media Object</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"pages/ui/modals.html\">Modals</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"pages/ui/notifications.html\">Notifications</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"pages/ui/pagination.html\">Pagination</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"pages/ui/preloaders.html\">Preloaders</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"pages/ui/progressbars.html\">Progress Bars</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"pages/ui/range-sliders.html\">Range Sliders</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"pages/ui/sortable-nestable.html\">Sortable & Nestable</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"pages/ui/tabs.html\">Tabs</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"pages/ui/thumbnails.html\">Thumbnails</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"pages/ui/tooltips-popovers.html\">Tooltips & Popovers</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"pages/ui/waves.html\">Waves</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"javascript:void(0);\" class=\"menu-toggle\">\r\n");
      out.write("                            <i class=\"material-icons\">assignment</i>\r\n");
      out.write("                            <span>Forms</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul class=\"ml-menu\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"pages/forms/basic-form-elements.html\">Basic Form Elements</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"pages/forms/advanced-form-elements.html\">Advanced Form Elements</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"pages/forms/form-examples.html\">Form Examples</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"pages/forms/form-validation.html\">Form Validation</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"pages/forms/form-wizard.html\">Form Wizard</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"pages/forms/editors.html\">Editors</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"javascript:void(0);\" class=\"menu-toggle\">\r\n");
      out.write("                            <i class=\"material-icons\">view_list</i>\r\n");
      out.write("                            <span>Tables</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul class=\"ml-menu\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"pages/tables/normal-tables.html\">Normal Tables</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"pages/tables/jquery-datatable.html\">Jquery Datatables</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"pages/tables/editable-table.html\">Editable Tables</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"javascript:void(0);\" class=\"menu-toggle\">\r\n");
      out.write("                            <i class=\"material-icons\">perm_media</i>\r\n");
      out.write("                            <span>Medias</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul class=\"ml-menu\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"pages/medias/image-gallery.html\">Image Gallery</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"pages/medias/carousel.html\">Carousel</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"javascript:void(0);\" class=\"menu-toggle\">\r\n");
      out.write("                            <i class=\"material-icons\">pie_chart</i>\r\n");
      out.write("                            <span>Charts</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul class=\"ml-menu\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"pages/charts/morris.html\">Morris</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"pages/charts/flot.html\">Flot</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"pages/charts/chartjs.html\">ChartJS</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"pages/charts/sparkline.html\">Sparkline</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"pages/charts/jquery-knob.html\">Jquery Knob</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"javascript:void(0);\" class=\"menu-toggle\">\r\n");
      out.write("                            <i class=\"material-icons\">content_copy</i>\r\n");
      out.write("                            <span>Example Pages</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul class=\"ml-menu\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"pages/examples/sign-in.html\">Sign In</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"pages/examples/sign-up.html\">Sign Up</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"pages/examples/forgot-password.html\">Forgot Password</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"pages/examples/blank.html\">Blank Page</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"pages/examples/404.html\">404 - Not Found</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"pages/examples/500.html\">500 - Server Error</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"javascript:void(0);\" class=\"menu-toggle\">\r\n");
      out.write("                            <i class=\"material-icons\">map</i>\r\n");
      out.write("                            <span>Maps</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul class=\"ml-menu\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"pages/maps/google.html\">Google Map</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"pages/maps/yandex.html\">YandexMap</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"pages/maps/jvectormap.html\">jVectorMap</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"javascript:void(0);\" class=\"menu-toggle\">\r\n");
      out.write("                            <i class=\"material-icons\">trending_down</i>\r\n");
      out.write("                            <span>Multi Level Menu</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul class=\"ml-menu\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"javascript:void(0);\">\r\n");
      out.write("                                    <span>Menu Item</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"javascript:void(0);\">\r\n");
      out.write("                                    <span>Menu Item - 2</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"javascript:void(0);\" class=\"menu-toggle\">\r\n");
      out.write("                                    <span>Level - 2</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <ul class=\"ml-menu\">\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <a href=\"javascript:void(0);\">\r\n");
      out.write("                                            <span>Menu Item</span>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <a href=\"javascript:void(0);\" class=\"menu-toggle\">\r\n");
      out.write("                                            <span>Level - 3</span>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                        <ul class=\"ml-menu\">\r\n");
      out.write("                                            <li>\r\n");
      out.write("                                                <a href=\"javascript:void(0);\">\r\n");
      out.write("                                                    <span>Level - 4</span>\r\n");
      out.write("                                                </a>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                        </ul>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"pages/changelogs.html\">\r\n");
      out.write("                            <i class=\"material-icons\">update</i>\r\n");
      out.write("                            <span>Changelogs</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"header\">LABELS</li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"javascript:void(0);\">\r\n");
      out.write("                            <i class=\"material-icons col-red\">donut_large</i>\r\n");
      out.write("                            <span>Important</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"javascript:void(0);\">\r\n");
      out.write("                            <i class=\"material-icons col-amber\">donut_large</i>\r\n");
      out.write("                            <span>Warning</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"javascript:void(0);\">\r\n");
      out.write("                            <i class=\"material-icons col-light-blue\">donut_large</i>\r\n");
      out.write("                            <span>Information</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li> -->\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- #Menu -->\r\n");
      out.write("            <!-- Footer -->\r\n");
      out.write("            <div class=\"legal\">\r\n");
      out.write("                <div class=\"copyright\">\r\n");
      out.write("                    &copy; 2016 - 2017 <a href=\"dashboard.jsp\">Grievance Redressal System</a>.\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"version\">\r\n");
      out.write("                    <b>Version: </b> Beta\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- #Footer -->\r\n");
      out.write("        </aside>\r\n");
      out.write("        <!-- #END# Left Sidebar -->\r\n");
      out.write("        <!-- Right Sidebar -->\r\n");
      out.write("       <!--  <aside id=\"rightsidebar\" class=\"right-sidebar\">\r\n");
      out.write("            <ul class=\"nav nav-tabs tab-nav-right\" role=\"tablist\">\r\n");
      out.write("                <li role=\"presentation\" class=\"active\"><a href=\"#skins\" data-toggle=\"tab\">SKINS</a></li>\r\n");
      out.write("                <li role=\"presentation\"><a href=\"#settings\" data-toggle=\"tab\">SETTINGS</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <div class=\"tab-content\">\r\n");
      out.write("                <div role=\"tabpanel\" class=\"tab-pane fade in active in active\" id=\"skins\">\r\n");
      out.write("                    <ul class=\"demo-choose-skin\">\r\n");
      out.write("                        <li data-theme=\"red\" class=\"active\">\r\n");
      out.write("                            <div class=\"red\"></div>\r\n");
      out.write("                            <span>Red</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li data-theme=\"pink\">\r\n");
      out.write("                            <div class=\"pink\"></div>\r\n");
      out.write("                            <span>Pink</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li data-theme=\"purple\">\r\n");
      out.write("                            <div class=\"purple\"></div>\r\n");
      out.write("                            <span>Purple</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li data-theme=\"deep-purple\">\r\n");
      out.write("                            <div class=\"deep-purple\"></div>\r\n");
      out.write("                            <span>Deep Purple</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li data-theme=\"indigo\">\r\n");
      out.write("                            <div class=\"indigo\"></div>\r\n");
      out.write("                            <span>Indigo</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li data-theme=\"blue\">\r\n");
      out.write("                            <div class=\"blue\"></div>\r\n");
      out.write("                            <span>Blue</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li data-theme=\"light-blue\">\r\n");
      out.write("                            <div class=\"light-blue\"></div>\r\n");
      out.write("                            <span>Light Blue</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li data-theme=\"cyan\">\r\n");
      out.write("                            <div class=\"cyan\"></div>\r\n");
      out.write("                            <span>Cyan</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li data-theme=\"teal\">\r\n");
      out.write("                            <div class=\"teal\"></div>\r\n");
      out.write("                            <span>Teal</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li data-theme=\"green\">\r\n");
      out.write("                            <div class=\"green\"></div>\r\n");
      out.write("                            <span>Green</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li data-theme=\"light-green\">\r\n");
      out.write("                            <div class=\"light-green\"></div>\r\n");
      out.write("                            <span>Light Green</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li data-theme=\"lime\">\r\n");
      out.write("                            <div class=\"lime\"></div>\r\n");
      out.write("                            <span>Lime</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li data-theme=\"yellow\">\r\n");
      out.write("                            <div class=\"yellow\"></div>\r\n");
      out.write("                            <span>Yellow</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li data-theme=\"amber\">\r\n");
      out.write("                            <div class=\"amber\"></div>\r\n");
      out.write("                            <span>Amber</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li data-theme=\"orange\">\r\n");
      out.write("                            <div class=\"orange\"></div>\r\n");
      out.write("                            <span>Orange</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li data-theme=\"deep-orange\">\r\n");
      out.write("                            <div class=\"deep-orange\"></div>\r\n");
      out.write("                            <span>Deep Orange</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li data-theme=\"brown\">\r\n");
      out.write("                            <div class=\"brown\"></div>\r\n");
      out.write("                            <span>Brown</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li data-theme=\"grey\">\r\n");
      out.write("                            <div class=\"grey\"></div>\r\n");
      out.write("                            <span>Grey</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li data-theme=\"blue-grey\">\r\n");
      out.write("                            <div class=\"blue-grey\"></div>\r\n");
      out.write("                            <span>Blue Grey</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li data-theme=\"black\">\r\n");
      out.write("                            <div class=\"black\"></div>\r\n");
      out.write("                            <span>Black</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div role=\"tabpanel\" class=\"tab-pane fade\" id=\"settings\">\r\n");
      out.write("                    <div class=\"demo-settings\">\r\n");
      out.write("                        <p>GENERAL SETTINGS</p>\r\n");
      out.write("                        <ul class=\"setting-list\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <span>Report Panel Usage</span>\r\n");
      out.write("                                <div class=\"switch\">\r\n");
      out.write("                                    <label><input type=\"checkbox\" checked><span class=\"lever\"></span></label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <span>Email Redirect</span>\r\n");
      out.write("                                <div class=\"switch\">\r\n");
      out.write("                                    <label><input type=\"checkbox\"><span class=\"lever\"></span></label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <p>SYSTEM SETTINGS</p>\r\n");
      out.write("                        <ul class=\"setting-list\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <span>Notifications</span>\r\n");
      out.write("                                <div class=\"switch\">\r\n");
      out.write("                                    <label><input type=\"checkbox\" checked><span class=\"lever\"></span></label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <span>Auto Updates</span>\r\n");
      out.write("                                <div class=\"switch\">\r\n");
      out.write("                                    <label><input type=\"checkbox\" checked><span class=\"lever\"></span></label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <p>ACCOUNT SETTINGS</p>\r\n");
      out.write("                        <ul class=\"setting-list\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <span>Offline</span>\r\n");
      out.write("                                <div class=\"switch\">\r\n");
      out.write("                                    <label><input type=\"checkbox\"><span class=\"lever\"></span></label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <span>Location Permission</span>\r\n");
      out.write("                                <div class=\"switch\">\r\n");
      out.write("                                    <label><input type=\"checkbox\" checked><span class=\"lever\"></span></label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </aside> -->\r\n");
      out.write("        <!-- #END# Right Sidebar -->\r\n");
      out.write("    </section>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
